require("banana.config.indent_blankline")
require("banana.config.treesitter")
require("banana.config.lsp")
require("banana.config.cmp")
require("banana.config.nvim_tree")
require("banana.config.telescope")
require("banana.config.presence")
require("banana.config.lualine")
require("banana.config.dashboard")
require("banana.config.comment")
require("banana.config.twilight")
require("banana.config.todo")
require("banana.config.vimtex")
require("banana.config.flutter")
require("banana.config.formatter")
require("banana.config.zen_mode")

-- no config --
require("colorizer").setup()
require("nvim-autopairs").setup()
require("lsp_signature").setup()
require("trouble").setup()
